---
- name: copy files
  become: yes
  become_user: root
  hosts: sss

  vars_files:
    - vars.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Create a directory if it does not exist
      file:
        path: /var/www/trur
        state: directory
        mode: 0777

    - name: Copy php vars_files
      copy:
        src: files/truruky/cucu2.txt
        dest: /var/www/trur/cucu2.txt
        owner: root
        group: root
        mode: 0777
