---
- name: default php
  become: yes
  become_user: root
  hosts: sss

  vars_files:
    - vars.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Create a directory if it does not exist
      file:
        path: /var/www/default
        state: directory
        mode: 0777

    - name: Copy php vars_files
      copy:
        src: files/d/
        dest: /var/www/default/
        owner: www-data
        group: www-data
        mode: 0777

    - name: Copy nginx confif file for truruky
      copy:
        src: files/d/default
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: 0777

    - name: Link folder
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded

