---
- name: MySQL
  hosts: all
  become: yes
  



  tasks:

  -  name: stop and disable
     service:
       name: mysql
       state: stopped
       enabled: no


  -  name: De-install pymysql via apt
     apt:
       name: python3-pymysql
       state: absent
       update_cache: yes


  -  name: De-install mysql via apt
     apt: 
       name: mysql-server
       state: absent 
       update_cache: yes
#-----------------зависает--------------------------------
# -  name: Execute command 1
#    shell: sudo -i
#    register: command_output-1
#
# -  name: Display command output
#    debug:
#      var: command_output-1.stdout_lines
#---------------------------------------------------------

  -  name: Execute command 2
     shell: service mysql stop
     register: command_output

  -  name: Display command 2 output
     debug:
       var: command_output.stdout_lines
#---------------------------------------------------------
  -  name: Execute command 3
     shell: killall -r  mysql mysqld_safe mysqld
     ignore_errors: yes
     register: command_output


  -  name: Display command 3 output
     debug:
       var: command_output.stdout_lines
#---------------------------------------------------------
  -  name: Execute command 4
     shell: apt-get --yes purge mysql-server mysql-clien
     ignore_errors: yes
     register: command_output

  -  name: Display command 4 output
     debug:
       var: command_output.stdout_lines
...


