---
- name: MySQL
  hosts: all
  become: yes
  vars:   
     mysql_root_password: password 
  

  tasks:
  -  name: Install mysql via apt
     apt: 
       name: mysql-server
       state: latest 
       update_cache: yes

 
  -  name: start and enable
     service:
        name: mysql
        state: started
        enabled: yes

  -  name: Install pymysql via apt
     apt:
        name: python3-pymysql
        state: latest
        update_cache: yes

  -  name: Set the local root password
     mysql_user:
        name: root
        password: 1
        login_user: root
        login_password: 2
        check_implicit_admin: yes
        login_unix_socket: /var/run/mysqld/mysqld.sock
        


...


