---
- name: MySQL
  hosts: all
  become: yes
  



  tasks:

  -  name: stop and disable
     service:
       name: mysql
       state: stopped
       enabled: no


  -  name: De-install pymysql via apt
     apt:
       name: python3-pymysql
       state: absent
       update_cache: yes


  -  name: De-install mysql via apt
     apt: 
       name: mysql-server
       state: absent 
       update_cache: yes

 

...


