---
- name: MySQL
  hosts: sss
  become: yes
  vars:   
     mysql_root_password: password 
  

  tasks:
  -  name: Install mysql via apt
     apt: 
       name: mysql-server
       state: latest 
       update_cache: yes

 
  -  name: start and enable
     service:
        name: mysql
        state: started
        enabled: yes

  -  name: Install pymysql via apt
     apt:
        name: python3-pymysql
        state: present
        update_cache: yes

  -  name: Set the local root password
     become: yes
     become_user: root
     community.mysql.mysql_user:
        login_user: 'root'
        login_password: '1'
        name: 'root'
        password: 'password'
        priv: '*.*:ALL,GRANT'
        host: 'localhost'
        state: present
        check_implicit_admin: yes
        login_unix_socket: /var/run/mysqld/mysqld.sock
        


...


