---
- name: MySQL
  hosts: sss
  become: yes

  tasks:

  - name: stop and disable
    service:
       name: mysql
       state: stopped
       enabled: no
  

  - name: Udalaem MySQL pakages
    apt:
       name:
         - mysql-server
         - mysql-client
         - python3-mysqldb
         - libmysqlclient-dev
       state: absent
       purge: yes
       autoremove: yes
    update_cache: yes