---
- name: MySQL
  hosts: all
  become: yes
  

  tasks:
  -  name: Install mysql via apt
     apt: 
       name: mysql-server
       state: latest 
       update_cache: yes

 
  -  name: start and enable
     service:
        name: mysql
        state: started
        enabled: yes

  

...


