---
- name: copy files
  become: yes
  become_user: root
  hosts: sss

  vars_files:
    - vars.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

#---------------------------------------------------------
    - name: Execute command pwd1
      shell: pwd
      register: command_output

    - name: Display command pwd1 output
      debug:
        var: command_output.stdout_lines
#--------------------------------------------------------- 

    - name: Execute command cd
      shell: cd /tmp
#---------------------------------------------------------
    - name: Execute command pwd2
      shell: pwd
      register: command_output

    - name: Display command pwd2 output
      debug:
        var: command_output.stdout_lines
#--------------------------------------------------------- 
   
    - name: download  
      get_url:
        url: https://files.phpmyadmin.net/phpMyAdmin/5.2.2/phpMyAdmin-5.2.2-all-languages.zip
        dest: /tmp/
        mode: 0755

#---------------------------------------------------------

    - name: Unarchive a file that is already on the remote machine
      ansible.builtin.unarchive:
        src: /tmp/phpMyAdmin-5.2.2-all-languages.zip
        dest: /tmp
        remote_src: yes

#---------------------------------------------------------
    - name: Execute command pwd3
      shell: pwd
      register: command_output

    - name: Display command pwd3 output
      debug:
        var: command_output.stdout_lines
#---------------------------------------------------------      

    - name: Create a directory if it does not exist
      file:
        path: /var/www/default/phpmyadmin
        state: directory
        mode: 0777
#---------------------------------------------------------

    - name: Copy files phpmyadmin
      copy:
        src: /tmp/phpMyAdmin-5.2.2-all-languages
        dest: /var/www/default/phpmyadmin
        remote_src: yes

