---
- name: create self sertificat
  become: yes
  become_user: root
  hosts: sss


  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: create private key
      openssl_privatekey:
         path: /etc/ssl/private/mycert.key
         size: 2048
    
    - name: create Certificate Signing Request (csr)
      openssl_csr:
         path: /etc/ssl/mycert.csr
         privatekey_path: /etc/ssl/private/mycert.key
         country_name: RU
         locality_name: Russian Federation
         organization_name: truruky
         email_address: master@truruky.ru
         common_name: truruky.ru
         
    - name: Generate a Self Signed OpenSSL certificate
      community.crypto.x509_certificate:
         path: /etc/ssl/certs/mycert.crt
         privatekey_path: /etc/ssl/private/mycert.key
         csr_path: /etc/ssl/mycert.csr
         provider: selfsigned


    - name: Copy ssl snippets
      copy:
        src: files/snippets/.
        dest: /etc/nginx/snippets/
   
    - name: Insert/Update configuration using a local file
      ansible.builtin.blockinfile:
        path: /etc/nginx/sites-available/truruky
        block: "{{ lookup('ansible.builtin.file', './files/truruky/new_frag') }}"
        marker: "## {mark} ANSIBLE MANAGED BLOCK"

    - name: Generate Diffie-Hellman parameters with the default size (4096 bits)
      community.crypto.openssl_dhparam:
        path: /etc/nginx/dhparam.pem

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded
    
