---
- name: copy files
  become: yes
  become_user: root
  hosts: sss

  vars_files:
    - vars.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Create a directory if it does not exist
      file:
        path: /var/www/trur
        state: directory
        mode: 0777

    - name: Copy php vars_files
      copy:
        src: files/truruky/tphp/
        dest: /var/www/trur/
        owner: neo
        group: neo
        mode: 0777

    - name: Copy nginx confif file for truruky
      copy:
        src: files/truruky/truruky
        dest: /etc/nginx/sites-available/truruky
        owner: neo
        group: neo
        mode: 0777

    - name: Link folder
      file:
        src: /etc/nginx/sites-available/truruky
        dest: /etc/nginx/sites-enabled/truruky
        state: link

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded

