---
- name: setup php
  become: yes
  hosts: sss

  vars_files:
    - vars.yml

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Create a directory if it does not exist
      file:
        path: /var/www/trur
        state: directory
        mode: 0777

    - name: Copy php vars_files
      copy:
        src: files/truruky/tphp/index.php
        dest: /var/www/trur/index.php
        owner: neo
        group: neo
        mode: 0777
